# Generated by Django 6.0.5 on 2026-05-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(verbose_name=20)),
                ('article_title', models.CharField(verbose_name=20)),
                ('article_annotation', models.CharField(verbose_name=200)),
                ('article_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Article_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(verbose_name=20)),
                ('article_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kernel_app.article')),
            ],
            options={
                'verbose_name': 'Article_Picture',
                'verbose_name_plural': 'Article_Pictures',
            },
        ),
    ]
