# Generated by Django 6.0.5 on 2026-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article_picture',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name=20),
        ),
        migrations.AlterField(
            model_name='article_picture',
            name='picture_id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name=20),
        ),
    ]
