# Generated by Django 6.0.5 on 2026-05-25 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0002_remove_article_id_remove_article_picture_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_preview_image',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 25, 15, 24, 30, 972605)),
        ),
        migrations.AddField(
            model_name='article_picture',
            name='picture',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_annotation',
            field=models.CharField(default='Loren ipsum', verbose_name=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(default='Loren ipsum'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='Шаблон заголовка', verbose_name=20),
        ),
    ]
