# Generated by Django 6.0.5 on 2026-05-27 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0003_article_article_preview_image_article_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 10, 59, 16, 290666)),
        ),
    ]
