# Generated by Django 6.0.5 on 2026-06-02 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0004_alter_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 2, 11, 0, 28, 355135)),
        ),
        migrations.RemoveField(
            model_name='article_picture',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article_picture',
            name='article_id',
            field=models.ManyToManyField(to='kernel_app.article'),
        ),
    ]
