# Generated by Django 6.0.5 on 2026-06-02 08:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0005_alter_article_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 2, 11, 21, 38, 372408)),
        ),
        migrations.RemoveField(
            model_name='article_picture',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article_picture',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kernel_app.article'),
            preserve_default=False,
        ),
    ]
