# Generated by Django 6.0.5 on 2026-06-10 09:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0006_alter_article_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='article_picture',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_annotation',
            field=models.CharField(default='Loren ipsum', max_length=200, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_preview_image',
            field=models.BinaryField(default=b'', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(default='Loren ipsum', verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='Шаблон заголовка', max_length=20, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 10, 12, 28, 39, 804915), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='article_picture',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel_app.article', verbose_name='Идентификатор новости'),
        ),
        migrations.AlterField(
            model_name='article_picture',
            name='picture',
            field=models.BinaryField(default=b'', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article_picture',
            name='picture_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Идентификатор изображения'),
        ),
    ]
