# Generated by Django 6.0.5 on 2026-06-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0007_alter_article_options_alter_article_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 10, 13, 10, 28, 982762), verbose_name='Дата'),
        ),
    ]
