# Generated by Django 6.0.5 on 2026-06-23 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0008_alter_article_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 9, 18, 23, 854577), verbose_name='Дата'),
        ),
    ]
